Sprint 6
Pussmal/MovieQuiz-ios pull request #3
Opened 2022-11-15 18:20 UTC by Pussmal

Добрый день!
Направляю на работу на проверку

2022-11-15 18:21 UTC, Pussmal commented
> Добрый день!
> Направляю на работу на проверку

2022-11-15 20:04 UTC, ABashkirova requested changes
Привет!

Все очень качественно сделано! Осталась небольшая ошибка ветвления: давай вызывать handler при получении ответа. 

Остальные комментарии по желанию.

2022-11-15 20:04 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    //            correctAnswer: true),
Гит все помнит, можно избавиться :)

2022-11-15 20:04 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private var mostPopularMovie = [MostPopularMovie]()
Эта форма предпочтительнее
```suggestion
    private var mostPopularMovie: [MostPopularMovie] = []
```

2022-11-15 20:04 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Не смотря на то что в уроке остались примеры, где нет weak-self у первого замыкания, я рекомендую его добавить. 
В данной реализации, конечно, утечек не возникает. Но замыкание потенциально может захватывать сильно контекст. Чтобы уберечь себя от "ошибок в будущем", стоит ослабить ссылку

```suggestion
        moviesLoader.loadMovies { [weak self] result in
```

2022-11-15 20:04 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Обращу внимание, что игра состоит из вопроса о рейтинге, на который отвечает пользователь, и контекста о фильме в виде постера. Без постера, пользователю будет затруднительно ответить на вопрос о рейтинге фильма верно.

В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно. Это состояние стоит обработать, например, с помощью алерта. Не забудьте, что алерт будет обновлять UI и это тоже нужно учесть, ровно также, как и прерывание функции.

2022-11-16 13:21 UTC, Pussmal commented
Александра, спасибо! На меня нашел невероятный тупняк, а что за ошибка ветвления? Я согласен вызывать handler после получения ответа, только какого?))) Я прям что-то не могу сообразить что надо поправить) по остальным комментариям принято, поработаю

2022-11-16 17:27 UTC, Pussmal commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let items: [MostPopularMovie]
Александра, спасибо! На меня нашел невероятный тупняк, а что за ошибка ветвления? Я согласен вызывать handler после получения ответа, только какого?))) Я прям что-то не могу сообразить что надо поправить) по остальным комментариям принято, поработаю

2022-11-17 08:06 UTC, ABashkirova commented on MovieQuiz/Services/MoviesLoader.swift
> +                guard let mostPopularMovies =  parseJSON(from: data) else { return }
@Pussmal вот это место я назвала ошибкой ветвления :) прошу прощения за выбор формулировки. 

Очень важно чтобы handler (замыкание, комплишен) обязательно вызвался в результе получения данных. Из-за простого return здесь он не вызовется из-за гвард (гвадр - оператор ветвления, такой же как и if else)

2022-11-17 08:07 UTC, ABashkirova commented
@Pussmal ответила выше

2022-11-17 08:29 UTC, Pussmal commented on MovieQuiz/Services/MoviesLoader.swift
> +                guard let mostPopularMovies =  parseJSON(from: data) else { return }
@ABashkirova 
Теперь все понял, спасибо! Правильным ли будет такое решение? парсю json и сразу проверяю массив чтобы не был пустым

в MoviesLoader создаю

    private enum MoviesLoaderError: Error {
        case jsonParseError
        case mostPopularMoviesItemsError
    }

  и далее:

           switch result {
            case .success(let data):
                guard let mostPopularMovies = parseJSON(from: data) else {
                    handler(.failure(MoviesLoaderError.jsonParseError))
                    return
                }
                
                guard !mostPopularMovies.items.isEmpty else {
                    handler(.failure(MoviesLoaderError.mostPopularMoviesItemsError))
                    return
                }
                
                handler(.success(mostPopularMovies))

2022-11-17 08:58 UTC, ABashkirova commented on MovieQuiz/Services/MoviesLoader.swift
> +                guard let mostPopularMovies =  parseJSON(from: data) else { return }
Да, это прям лучший вариант (gold-way-style)

2022-11-19 06:43 UTC, Pussmal commented
@ABashkirova 
Александра, здравствуйте!
Направил на проверку работу, ошибку ветвления поправил, над остальными комментариями еще поработаю, уезжаю на несколько дней, боюсь не успеть по срокам по этому направил с учетом исправления главной ошибки

2022-11-19 14:42 UTC, ABashkirova approved these changes
Принято!

2022-11-25 07:24 UTC, merged